
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - ${WRITABLE_DIR}/mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "3306:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      timeout: 5s
#      retries: 10

  fastapi:
    image: satto-registry.kr.ncr.ntruss.com/satto-server-fastapi:latest
    pull_policy: always
    container_name: fastapi-app
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ${WRITABLE_DIR}/logs/app:/data/logs/app
    command: >
      sh -c "
        gunicorn src.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    env_file:
      - .env
