"""add lotto draws and statistics

Revision ID: 47e81b19f851
Revises: ec45a4f91988
Create Date: 2025-08-05 23:23:51.373015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e81b19f851'
down_revision: Union[str, Sequence[str], None] = 'ec45a4f91988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotto_draws',
    sa.Column('round', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('draw_date', sa.Date(), nullable=False),
    sa.Column('num1', sa.Integer(), nullable=False),
    sa.Column('num2', sa.Integer(), nullable=False),
    sa.Column('num3', sa.Integer(), nullable=False),
    sa.Column('num4', sa.Integer(), nullable=False),
    sa.Column('num5', sa.Integer(), nullable=False),
    sa.Column('num6', sa.Integer(), nullable=False),
    sa.Column('bonus_num', sa.Integer(), nullable=False),
    sa.Column('first_prize_amount', sa.Integer(), nullable=False),
    sa.Column('total_winners', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('bonus_num BETWEEN 1 AND 45', name='bonus_num_range_check'),
    sa.CheckConstraint('num1 BETWEEN 1 AND 45', name='num1_range_check'),
    sa.CheckConstraint('num2 BETWEEN 1 AND 45', name='num2_range_check'),
    sa.CheckConstraint('num3 BETWEEN 1 AND 45', name='num3_range_check'),
    sa.CheckConstraint('num4 BETWEEN 1 AND 45', name='num4_range_check'),
    sa.CheckConstraint('num5 BETWEEN 1 AND 45', name='num5_range_check'),
    sa.CheckConstraint('num6 BETWEEN 1 AND 45', name='num6_range_check'),
    sa.PrimaryKeyConstraint('round')
    )
    op.create_table('lotto_statistics',
    sa.Column('num', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('main_count', sa.Integer(), nullable=True),
    sa.Column('bonus_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('last_round', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('num BETWEEN 1 AND 45', name='num_range_check'),
    sa.PrimaryKeyConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lotto_statistics')
    op.drop_table('lotto_draws')
    # ### end Alembic commands ###
