"""add_unique_constraint_to_user_daily_fortune_detail

Revision ID: 50ef02f95f5c
Revises: 578233fccdf8
Create Date: 2025-08-22 19:26:03.866093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ef02f95f5c'
down_revision: Union[str, Sequence[str], None] = '578233fccdf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk_user_daily_fortune_detail_user_date', 'user_daily_fortune_detail', ['user_id', 'fortune_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uk_user_daily_fortune_detail_user_date', 'user_daily_fortune_detail', type_='unique')
    # ### end Alembic commands ###
