"""add is_read, read_at field to lotto recommendation table

Revision ID: 578233fccdf8
Revises: 926bb28822d1
Create Date: 2025-08-18 00:37:25.201315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578233fccdf8'
down_revision: Union[str, Sequence[str], None] = '926bb28822d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lotto_recommendations', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('lotto_recommendations', sa.Column('read_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lotto_recommendations', 'read_at')
    op.drop_column('lotto_recommendations', 'is_read')
    # ### end Alembic commands ###
