"""add user daily fortune summary

Revision ID: 5b71f35cc0bc
Revises: 5f0e5c266c72
Create Date: 2025-08-12 13:23:11.547868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b71f35cc0bc'
down_revision: Union[str, Sequence[str], None] = '5f0e5c266c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
