"""add daily fortune resources

Revision ID: 5f0e5c266c72
Revises: 05818a33a6e5
Create Date: 2025-08-09 13:17:47.255785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f0e5c266c72'
down_revision: Union[str, Sequence[str], None] = '05818a33a6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_fortune_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='운세 고유 ID'),
    sa.Column('publish_date', sa.Date(), nullable=False, comment='운세 발행 날짜'),
    sa.Column('fortune_type', sa.Enum('GUIIN_INITIAL', 'LUCKY_OBJECT', 'PERFECT_TIMING', 'TABOO_OF_DAY', name='fortunetype'), nullable=False, comment='운세 항목 종류 (귀인의 초성 등)'),
    sa.Column('image_url', sa.String(length=1000), nullable=False, comment='이미지 URL 또는 경로'),
    sa.Column('description', sa.String(length=1000), nullable=False, comment='운세 설명'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(description) > 0', name='ck_fortune_description_len'),
    sa.CheckConstraint('length(image_url) > 0', name='ck_fortune_image_url_len'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_fortune_resources')
    # ### end Alembic commands ###
