"""add atm table

Revision ID: 65357b1f6271
Revises: a1b2c3d4e5f6
Create Date: 2026-02-08 16:37:25.093868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65357b1f6271'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atm',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trns_org_code', sa.String(length=3), nullable=False),
    sa.Column('org_type_code', sa.String(length=3), nullable=False),
    sa.Column('atm_no', sa.String(length=20), nullable=False),
    sa.Column('dup_atm_no', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('mob_cash_card_psb_yn', sa.String(length=1), nullable=True),
    sa.Column('istl_loc_type_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('lotto_store_winnings', 'store_id',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='판매점 ID',
               existing_nullable=False)
    op.alter_column('lotto_store_winnings', 'round',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='당첨 회차',
               existing_nullable=False)
    op.alter_column('lotto_store_winnings', 'prize_rank',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='당첨 등수 (1 또는 2)',
               existing_nullable=False)
    op.alter_column('lotto_store_winnings', 'prize_type',
               existing_type=mysql.ENUM('auto', 'manual', 'semi'),
               comment=None,
               existing_comment='당첨 유형',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'id',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='판매점 ID (RTLRID)',
               existing_nullable=False)
    op.alter_column('lotto_stores', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='판매점 이름',
               existing_nullable=False)
    op.alter_column('lotto_stores', 'latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               comment=None,
               existing_comment='위도',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               comment=None,
               existing_comment='경도',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'road_address',
               existing_type=mysql.VARCHAR(length=200),
               comment=None,
               existing_comment='도로명주소',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'lot_address',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='지번주소',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'region1',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='시/도',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'region2',
               existing_type=mysql.VARCHAR(length=30),
               comment=None,
               existing_comment='시/군/구',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'region3',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='동/읍/면',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='전화번호',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_count',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1등 배출 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_auto',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1등 자동 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_manual',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1등 수동 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_semi',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1등 반자동 횟수',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lotto_stores', 'first_prize_semi',
               existing_type=mysql.INTEGER(),
               comment='1등 반자동 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_manual',
               existing_type=mysql.INTEGER(),
               comment='1등 수동 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_auto',
               existing_type=mysql.INTEGER(),
               comment='1등 자동 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'first_prize_count',
               existing_type=mysql.INTEGER(),
               comment='1등 배출 횟수',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='전화번호',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'region3',
               existing_type=mysql.VARCHAR(length=20),
               comment='동/읍/면',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'region2',
               existing_type=mysql.VARCHAR(length=30),
               comment='시/군/구',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'region1',
               existing_type=mysql.VARCHAR(length=20),
               comment='시/도',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'lot_address',
               existing_type=mysql.VARCHAR(length=100),
               comment='지번주소',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'road_address',
               existing_type=mysql.VARCHAR(length=200),
               comment='도로명주소',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'longitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               comment='경도',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'latitude',
               existing_type=mysql.DECIMAL(precision=10, scale=7),
               comment='위도',
               existing_nullable=True)
    op.alter_column('lotto_stores', 'name',
               existing_type=mysql.VARCHAR(length=100),
               comment='판매점 이름',
               existing_nullable=False)
    op.alter_column('lotto_stores', 'id',
               existing_type=mysql.VARCHAR(length=20),
               comment='판매점 ID (RTLRID)',
               existing_nullable=False)
    op.alter_column('lotto_store_winnings', 'prize_type',
               existing_type=mysql.ENUM('auto', 'manual', 'semi'),
               comment='당첨 유형',
               existing_nullable=True)
    op.alter_column('lotto_store_winnings', 'prize_rank',
               existing_type=mysql.INTEGER(),
               comment='당첨 등수 (1 또는 2)',
               existing_nullable=False)
    op.alter_column('lotto_store_winnings', 'round',
               existing_type=mysql.INTEGER(),
               comment='당첨 회차',
               existing_nullable=False)
    op.alter_column('lotto_store_winnings', 'store_id',
               existing_type=mysql.VARCHAR(length=20),
               comment='판매점 ID',
               existing_nullable=False)
    op.drop_table('atm')
    # ### end Alembic commands ###
