"""add_user_daily_fortune_detail_table

Revision ID: 926bb28822d1
Revises: de9ee05d86b4
Create Date: 2025-08-13 21:13:08.667387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '926bb28822d1'
down_revision: Union[str, Sequence[str], None] = 'de9ee05d86b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_fortune_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='운세 상세 기록 고유 ID'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='유저 ID'),
    sa.Column('fortune_date', sa.Date(), nullable=False, comment='운세 날짜'),
    sa.Column('fortune_score', sa.Integer(), nullable=False, comment='운세 점수'),
    sa.Column('fortune_comment', sa.String(length=1000), nullable=False, comment='운세 코멘트'),
    sa.Column('fortune_details', sa.JSON(), nullable=False, comment='운세 상세 정보 (JSON)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('fortune_score >= 0 AND fortune_score <= 100', name='ck_fortune_score_range'),
    sa.CheckConstraint('length(fortune_comment) > 0', name='ck_fortune_comment_len'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_daily_fortune_detail')
    # ### end Alembic commands ###
