"""add user daily fortune summary

Revision ID: e082b238c1e3
Revises: 5f0e5c266c72
Create Date: 2025-08-12 16:15:00.678563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e082b238c1e3'
down_revision: Union[str, Sequence[str], None] = '5f0e5c266c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_fortune_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='운세 기록 고유 ID'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='유저 ID'),
    sa.Column('daily_fortune_resource_id', sa.Integer(), nullable=False, comment='운세 리소스 ID'),
    sa.Column('fortune_date', sa.Date(), nullable=False, comment='운세 날짜'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['daily_fortune_resource_id'], ['daily_fortune_resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_daily_fortune_summary')
    # ### end Alembic commands ###
