"""add user field

Revision ID: ec45a4f91988
Revises: 41c657cd9376
Create Date: 2025-07-29 23:46:58.201303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ec45a4f91988'
down_revision: Union[str, Sequence[str], None] = '41c657cd9376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('gender', sa.Enum('F', 'M', name='gender'), nullable=False))
    op.add_column('users', sa.Column('four_pillar', sa.JSON(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=255),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'four_pillar')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_date')
    # ### end Alembic commands ###
