"""add columns to atm table

Revision ID: fc3ca4174435
Revises: 65357b1f6271
Create Date: 2026-02-09 01:05:20.867929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc3ca4174435'
down_revision: Union[str, Sequence[str], None] = '65357b1f6271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atm', sa.Column('place_name', sa.String(length=255), nullable=False))
    op.add_column('atm', sa.Column('category_name', sa.String(length=255), nullable=True))
    op.add_column('atm', sa.Column('category_group_code', sa.String(length=16), nullable=True))
    op.add_column('atm', sa.Column('category_group_name', sa.String(length=64), nullable=True))
    op.add_column('atm', sa.Column('phone', sa.String(length=64), nullable=True))
    op.add_column('atm', sa.Column('address_name', sa.String(length=255), nullable=True))
    op.add_column('atm', sa.Column('road_address_name', sa.String(length=255), nullable=True))
    op.add_column('atm', sa.Column('place_url', sa.String(length=255), nullable=True))
    op.alter_column('atm', 'id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index('idx_atm_lat_lon', 'atm', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_atm_place_name', 'atm', ['place_name'], unique=False)
    op.drop_column('atm', 'org_type_code')
    op.drop_column('atm', 'istl_loc_type_code')
    op.drop_column('atm', 'name')
    op.drop_column('atm', 'atm_no')
    op.drop_column('atm', 'trns_org_code')
    op.drop_column('atm', 'mob_cash_card_psb_yn')
    op.drop_column('atm', 'dup_atm_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atm', sa.Column('dup_atm_no', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('atm', sa.Column('mob_cash_card_psb_yn', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('atm', sa.Column('trns_org_code', mysql.VARCHAR(length=3), nullable=False))
    op.add_column('atm', sa.Column('atm_no', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('atm', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('atm', sa.Column('istl_loc_type_code', mysql.VARCHAR(length=3), nullable=True))
    op.add_column('atm', sa.Column('org_type_code', mysql.VARCHAR(length=3), nullable=False))
    op.drop_index('idx_atm_place_name', table_name='atm')
    op.drop_index('idx_atm_lat_lon', table_name='atm')
    op.alter_column('atm', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('atm', 'place_url')
    op.drop_column('atm', 'road_address_name')
    op.drop_column('atm', 'address_name')
    op.drop_column('atm', 'phone')
    op.drop_column('atm', 'category_group_name')
    op.drop_column('atm', 'category_group_code')
    op.drop_column('atm', 'category_name')
    op.drop_column('atm', 'place_name')
    # ### end Alembic commands ###
